Add RequiredFrom option to opendmarc.conf
trusteddomainproject/OpenDMARC pull request #147
Opened 2021-03-29 08:28 UTC by manu0401

If RequiredFrom is set, opendmarc will reject messages that lack
a From header from which a valid domain can be extracted. This
is a subset of the full RFC5322 requirements enforced by the
RequiredHeaders option.

While non RFC5322-compliant messages are too common to make
RequiredHeaders always usable, the check on the From header
remains especially valuable. It makes sure forged domain messages
cannot evade the filter by just omitting the From header and relying
on the MTA to fill it by a copy from the enveloppe header.

2021-03-29 11:45 UTC, dilyanpalauzov commented
Why do not you use the RequiredHeaders option for this?

2021-03-29 12:42 UTC, manu0401 commented
????? ???????? ***@***.***> wrote:

> Why do not you use the RequiredHeaders option for this?

I just got burned by RequiredHeaders which rejects a lot of valid
e-mails that violate RFC5322 (double headers are the most common
offence). Obviously it does not fit for me.

But as noted in the commit message, testing the From header is
especially important, otherwise messages can slip through opendmarc by
just omitting it. The MTA will copy the enveloppe sender into a new From
header, and no check will be done wether it is legit or not.

-- 
Emmanuel Dreyfus
http://hcpnet.free.fr/pubz
***@***.***

2021-03-29 13:05 UTC, dilyanpalauzov commented
Please extend the documentation for a discussion, what kind of advantages offer the new option over RequiredHeaders .  Who will want to accept an email with many Message-Id headers, but with correct From?

2021-03-29 13:15 UTC, manu0401 commented
????? ???????? ***@***.***> wrote:

> Please extend the documentation for a discussion, what kind of advantages
> offer the new option over RequiredHeaders .  Who will want to accept an
> email with many Message-Id headers, but with correct From?

You take it the wrong way around :-)

I can live with a buggy message with multiple Message-Id, but today, a
message with a missing From header will go through opendmarc unblocked,
the MTA will copy the envelope From into a new header From, and the user
will see a forged sender domain even if it is supposed to be protected
by DMARC.

-- 
Emmanuel Dreyfus
http://hcpnet.free.fr/pubz
***@***.***

2022-02-06 15:44 UTC, ghen2 commented
See https://github.com/trusteddomainproject/OpenDMARC/issues/202 which applies to this PR as well.

2022-02-06 17:19 UTC, ghen2 requested changes

2022-02-06 17:19 UTC, ghen2 commented on opendmarc/opendmarc.conf.5.in
> +without effect if
"This option", not "options"

2022-02-06 17:19 UTC, ghen2 commented on opendmarc/opendmarc.conf.sample
> +##  options is without effect if RequiredHeaders is set to "true".
"This option", not "options"

2022-02-07 09:31 UTC, ghen2 approved these changes

2026-05-27 06:00 UTC, thegushi commented
Thank you for this - it's a good, focused feature that fills a real gap between doing nothing and enforcing all of RFC5322.

We've implemented this in PR #343. The logic is taken directly from your patch; the only reason we didn't apply it verbatim is that the surrounding code had changed since you opened this (notably the RequiredHeaders error message improvements), so the patch didn't apply cleanly. The changes are functionally identical to what you proposed.

Closing in favour of #343.

2026-05-27 06:00 UTC, closed without merging